// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var RepoData$ReactHooksTemplate = require("./RepoData.bs.js");
var RepoItem$ReactHooksTemplate = require("./RepoItem.bs.js");

function App(Props) {
  var match = React.useState((function () {
          return undefined;
        }));
  var setRepoData = match[1];
  var repoData = match[0];
  React.useEffect((function () {
          RepoData$ReactHooksTemplate.fetchRepos(/* () */0).then((function (repoData) {
                    Curry._1(setRepoData, (function (_prev) {
                            return repoData;
                          }));
                    return Promise.resolve(/* () */0);
                  })).catch((function (err) {
                  console.log("An error occurred: " + String(err));
                  return Promise.resolve(/* () */0);
                }));
          return undefined;
        }), ([]));
  var repoItems = repoData !== undefined ? $$Array.map((function (repo) {
            return React.createElement(RepoItem$ReactHooksTemplate.make, {
                        repo: repo,
                        key: repo[/* full_name */0]
                      });
          }), repoData) : "Loading...";
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Reason Projects"), repoItems);
}

var make = App;

exports.make = make;
/* react Not a pure module */
